### ISSUE TITLE
關於 peek.js 的小問題

### ISSUE THREAD

**Issue by Ichi1234567** [polydice/peeker#1]
邏輯和使用上看起來沒什摸問題，有稍微試過幾個瀏覽器，應該也沒啥問題！耶~ w+
### 各種可能的小問題

可以參考下大家的 style guide [node-style-guid](https://github.com/felixge/node-style-guide)、或者使用 jslint。(雖然、我有時候也不太注意，style 也改過很多次...)
- [x] 請愛用匿名 function 包在最外層，避免 global 變數氾濫。
- [x] js... 變數大部份還是 camel case。
- [x] 像這特定 element 存在才有執行價值的程式，一般會在一開始判定 element 存不存在，不存在就直接 return 啦。可以直接給個變數定義，這樣就可以改寫 `peek_initialize`。
- [x] 一般 listener 會放在初始化之後，避免種種可能的隱藏性問題。
- [x] 一般不會用 `new String()`，`new Object()`，初始化這種基礎型別。
  1. 太多餘、不直觀。
  2. 印象中跟實作的方式有關。
- [x] `localStorage.getItem` or `localStorage["peek_status"]`，選其中一種方式就好了。
- `peek_toggler`
  - [x] 參數 mode 沒有用到
  - [x] `peek_element.style` 還是 `peek.style`
### 以下是不需要很介意的主觀認定
- 比較冗長又會重複使用的資料，可以考慮定義個變數。
- 有些簡短又不太用到的 method 很像不必要定義，會眼花。

以上！

**Comment by frozenfung** [comment]
根據昨天的討論做了一些修改
再麻煩你有空的時候幫忙看一下
感謝
@Ichi1234567

**Comment by Ichi1234567** [comment]
耶~ 可以 close 了~！
